<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Zaiweis-MacBook-Air.local" ignored="0" name="Test" tests="2" failures="2" timestamp="11 Jul 2021 04:41:58 GMT" time="2.433" errors="0">
  <testcase name="test_calculate_total_delivery_price_with_express_api" time="1.299" classname="run.test.api.TestAuspostApi">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at run.test.api.TestAuspostApi.test_calculate_total_delivery_price_with_express_api(TestAuspostApi.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- test_calculate_total_delivery_price_with_express_api -->
  <testcase name="test_calculate_total_delivery_price_with_regual_api" time="0.186" classname="run.test.api.TestAuspostApi">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at run.test.api.TestAuspostApi.test_calculate_total_delivery_price_with_regual_api(TestAuspostApi.java:68)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- test_calculate_total_delivery_price_with_regual_api -->
</testsuite> <!-- Test -->
